### ISSUE TITLE
[FEATURE] Add Privacy Policy to "More" dropdown

### ISSUE THREAD

**Issue by kaanrkaraman** [Discord-Templates/Bugs-and-Feedbacks#13] opened 2020-06-02 18:12 UTC
I think a Privacy Policy link in "More" dropdown on navigation bar would be nice.
Also in https://discordtemplates.com/legal/terms, adding a link of Privacy Policy here ( http://snowy.is-online.me/i/q7m0nvb5augfvsd.png ) as a clickable would be very nice.

**Comment by heyimnitho** [comment] 2020-06-02 18:15
#12 - Same thing happens on 'Add Template' page. There's a under-lined text, named as "FAQ" and it corrently redirects to `https://discordtemplates.com/faq` but it seems like these pages aren't added on website.

**Comment by CanCodes** [comment] 2020-06-02 18:16
Shortly, Privacy and FAQ pages are not in the website right now. this also closes #12

_Originally posted by @CanCodes in https://github.com/Discord-Templates/Bugs-Feedbacks/issues/11#issuecomment-637718681_

**Comment by eggsy** [comment] 2020-06-02 18:17
We are still working on our "Privacy Policy" page. Website itself is in public testing right now. Thank you for your feedback but this is not a bug and will be fixed as soon as we finish writing our Privacy.

@thisisnithy 
And thank you for reporting that. That will be fixed in the next update.

**Closed as completed by CanCodes** 2020-06-02 18:16 UTC
Labels: feature request
