### ISSUE TITLE
[BUG] Incorrect Text Shapes

### ISSUE THREAD

**Issue by smilefate** [Discord-Templates/Bugs-and-Feedbacks#19] opened 2020-06-03 11:38 UTC
**Describe the bug**
Markdown / Messletters / Formatting Text.. (Sorry I don't know the exact ENG pronunciation.) Everything looks fine in the editor. However, when we share errors occur. **In short, screenshots will explain everything better.**

**To Reproduce**
1. Create a project. (Open the editing tab if you have a project)
2. Write something in the long description of your project.
3. Shape the article you write. (Bold / Italic / Underline / Strikethrough)
4. Save your project and see the final version. You will see the problem -_-

**Expected behavior**
Text styling was supposed to be successful

**Screenshots**
[Editor View and Preview](https://smilefate.is-inside.me/0lPM5u3P.png) & [The view after sharing](https://smilefate.is-inside.me/GY2vcI5A.png)

**Desktop:**
 - OS: [Windows]
 - Browser [Chrome Beta]
 - Version [84.0.4147.30]

**Note**: Writing limit does not match the specified limit. It gave the error "Api" but I couldn't get a screenshot. There was only an extra part of the article, I deleted it (I had not reached the writing limit before deleting it. I had 3 more rights to reach the limit) and I wanted to try again by pressing the "Save" button and it was successful.

**Comment by CanCodes** [comment] 2020-06-03 12:05
Could not reproduce the API error, can you send a video or a gif of you reproducing the API issue please? For the preview part, it has some issues and will be fixed as soon as possible. Thank you for reporting this issue.

**Comment by smilefate** [comment] 2020-06-03 12:42
I am currently editing through the template I have shared. and did not make a warning about Api. But when creating a new template, Api was showing the warning.

It does not currently display warnings, but stuck on the loading screen
https://streamable.com/1hc0ha
https://streamable.com/2djbk6

**Comment by eggsy** [comment] 2020-06-03 12:44
check your console F12

**Comment by smilefate** [comment] 2020-06-03 12:46
https://smilefate.is-inside.me/vQjp2Cnp.png

**Comment by eggsy** [comment] 2020-06-03 14:20
Will be fixed in the next update.

**Closed as completed by eggsy** 2020-06-03 14:20 UTC
Labels: bug, question
